development: &development
    host: localhost
    port: 8000
    protocol: stomp
    stomp_host: localhost
    stomp_port: 61613
    stomp_user: nanite
    stomp_password: testing 
    reactor: select
    morbidq: 0
    restrict_access: 0

test:
    <<: *development

production:
    host: your.domain.com
    port: 8000
    protocol: stomp
    stomp_host: your.stomp.domain.com
    stomp_port: 61613
    reactor: epoll
    morbidq: 0
    restrict_access: 1
 
